### ISSUE TITLE
Control Panel in World Doesn't Function

### ISSUE THREAD

**Issue by metroidmen** [planaria/vrc-receiver#1]
Cannot control any of the sliders in the world.

May be related to the depth of the photo quilt at being entirely off after saving.

**Comment by planaria** [comment]
You can only operate the slider while the Quick Menu is open.

**Comment by metroidmen** [comment]
> You can only operate the slider while the Quick Menu is open.

Oh! Good to know, I will keep that in mind! Any ideas why everything is “out of focus” when the quilt is pulled into the looking glass? It looked fine on the virtual portrait in the world, but once saved and placed on the portrait itself, it’s all out of focus. 

Or is this because the default settings on the panel, as they were unable to be changed at the time these photos were taken.

thanks!

**Comment by planaria** [comment]
You can reduce the blur by standing on the very edge of the shooting box.
This blur depends on the accuracy of the Looking Glass lenticular lens.
